---
title: Online Courses
author: Marie
date: 2018-05-30T13:39:46+02:00
slug: online-courses
categories: [My-Learning-Path]
tags: []
main: "main"
banner: "img/banners/online_courses.jpg"
---




# Online course providers:

* [Coursera](https://www.coursera.org)
* [edX](https://www.edx.org)
* [Udacity](https://www.udacity.com)
* [DataCamp](https://www.datacamp.com)
* [Udemy](https://www.udemy.com/)
* [Kaggle](https://www.kaggle.com/learn)

# Courses I've Taken
<!-- <i class="fa fa-star-o"></i> -->
* **[Machine Learning](https://www.coursera.org/learn/machine-learning)** by [Coursera](https://www.coursera.org) and Stanford University
    + **My Rating**: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
    + **Cost**: $102 (for certificate / free to audit)
    + **Time to Complete**: 11 weeks
    + **Comments**: This is a great course for understanding how different algorithms work; I would like to take this course again

* **Computing for Data Analysis** (no longer offered) by [Coursera](https://www.coursera.org) and John Hopkins University
    + **My Rating**: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
    + **Cost**: free to audit
    + **Time to Complete**: 4 weeks
    + **Comments**: The courses now seem to make up the [Data Science Specialization](https://www.coursera.org/specializations/jhu-data-science) with a suggested timeline of 9 months
    
    
* **[Maps and the Geospatial Revolution](https://www.coursera.org/learn/geospatial)** by [Coursera](https://www.coursera.org) and The Pennsylvania State University
    + **My Rating**: <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
    + **Cost**: $63 (for certificate / free to audit)
    + **Time to Complete**: 5 weeks
    + **Comments**: 
    
    
* **[Neural Networks and Deep Learning (Course 1 Deep Learning Specialisation)](https://www.coursera.org/learn/neural-networks-deep-learning)** by Coursera
    + **Cost**: Free to audit
    + **Topics**: Neural networks
    + **Programming Language**: Python
    + **Time to Complete**: 4 weeks of study, 3-6 hours a week  
    + **Comments**: Clear explanations and spoon-fed assignments.    
    
* **[Improving Deep Neural Networks: Hyperparameter tuning, Regularization and Optimization (Course 2 Deep Learning Specialisation)](https://www.coursera.org/learn/deep-neural-network)** by Coursera
    + **Cost**: Free to audit
    + **Topics**: Initialization, L2 and dropout regularization, Batch normalization, gradient checking.
Optimization algorithms: mini-batch gradient descent, Momentum, RMSprop and Adam.  TensorFlow. 
    + **Programming Language**: Python
    + **Time to Complete**: 3 weeks, 3-6 hours per week   
    
* **[Structuring Machine Learning Projects (Course 3 Deep Learning Specialisation)](https://www.coursera.org/learn/machine-learning-projects)** by Coursera
    + **Cost**: Free to audit
    + **Topics**: How to build a successful machine learning project
    + **Programming Language**: Python
    + **Time to Complete**: 2 weeks of study, 3-4 hours/week         
    
    
Credits: I borrowed the layout of this page from [Amber Thomas](http://amber.rbind.io/blog/2016/12/17/dscourses/)